{
    "data":{
    "1":"Bầu trời xanh, làn mây trắng. Anh yêu nắng hay yêu em?",
    "2":"Nhờ có nắng mới thấy cầu vồng. Nhờ có anh mới thấy màu hạnh phúc.",
    "3":"Soái ca là của ngôn tình. Còn anh thì chỉ của mình em thôi.",
    "4":"Ba mươi chưa phải là Tết. Không làm bạn đâu phải là hết, còn có thể làm người yêu mà",
    "5":"Nắng đã có mũ, mưa đã có ô, còn em sẽ có ai?",
    "6":"Mùa xuân thì có hoa đào\nNhưng cho anh hỏi mùa nào có em",
    "7":"Tết về xuân cũng đã sang\nGiờ đây chỉ muốn rước nàng về dinh",
    "8":"Ngoài kia gió rét sương sa. Về đây có nắng, có nhà, có em",
    "9":"Chạy đâu cho khỏi mưa rào. Chạy đâu cho khỏi sà vào tay anh",
    "10":"Em đây rất thích màu hồngg\nThích luôn cả việc anh làm chồng emmmm",
    "11":"Hãy gọi em là Dove\nVì em sẽ giúp phục hồi hư tổn từ sâu bên trong",
    "12":"Em ăn cơm chưa?",
    "13":"Nàng bảo tôi thiểu năng\nThực ra tôi thieu nang",
    "14":"Giá anh mở tiệm cầm đồ\nĐể em đây đến giả vờ cầm tay",
    "15":"Thiếu 500 nghìn là anh tròn một củ\nThiếu em nữa là anh đủ một đôi.",
    "16":"Cho em một cốc trà đào\nTiện cho anh hỏi lối vào tim em!",
    "17":"Trung thu anh vẫn một mình\nNếu em vẫn vậy thì mình đi chung.",
    "18":"Anh có một siêu năng lực\nLà siêu thích em",
    "19":"Tớ vừa hoá đá con tim\nSao cậu xuất hiện làm chìm giá băng.",
    "20":"Anh bận tất cả mọi điều\nNhưng vẫn luôn rảnh để nhớ đến em.",
    "21":"Vertor chỉ có một chiều\nEm dân chuyên toán chỉ yêu 1 người.",
    "22":"Thiếu ăn, chim tìm con sâu.\nThiếu em, anh sầu con tim!",
    "23":"Ô tô thì đã có chỗ đỗ.\nCòn em thì đã đỗ trong tim anh!",
    "24":"Anh mua con heo đất.\nTiền anh đem cất, sau này cưới em.",
    "25":"Anh có một siêu năng lực đó là: Nhắm mắt lại sẽ nhìn thấy em!",
    "26":"Họ thích nghe nhạc có lời, nhưng anh lại thích trọn đời có em!",
    "27":"Muốn mặn thì ăn muối.\nMuốn đắm đuối thì yêu anh!",
    "28":"Hôm nay anh học toán hình.\nTròn, vuông chẳng có mà toàn hình bóng em!",
    "29":"Trứng rán cần mỡ, bắp cần bơ.\nYêu không cần cớ, cần cậu cơ!",
    "30":"Mượn xe nhớ đổ đầy bình.\nMượn tim nhớ đổ đầy tình giúp anh!",
    "31":"Anh đây chẳng thích nhiều lời.\nNhìn em là biết cả đời của anh!",
    "32":"Đen Vâu thì muốn về quê trồng rau, nuôi cá.\nCòn anh thì muốn về hỏi ba má cưới em.",
    "33":"Nếu trái tim là một nhà tù.\nAnh nguyện bị kết án chung thân",
    "34":"Nếu ai đó bảo xinh đẹp thì phải đi tù\nThì em xứng đáng nhận tù chung thân",
    "35":"Có một đốm lửa nhỏ.\nThắp lên hạnh phúc to.\nEm đã có ai ngỏ.\nHay là để anh lo.",
    "36":"Cuộc đời em là một phương trình. Nếu thiếu anh sẽ trở nên vô nghiệm.",
    "37":"Tình yêu em dành cho anh giống như sức nóng ở sa mạc Sahara vậy đó.",
    "38":"Một cộng một bằng hai.\nEm cộng anh thì thành một cặp.",
    "39":"Cây đa, giếng nước sân đinh.\nKhi nào em hết một mình đây anh?",
    "40":"Ước gì trái tim mình là nước\nĐể không có những vết xước bên trong!\nNếu cảm xúc mà diễn tả được thành lời\nThì… con người ta đã chẳng phải gượng cười khi đau đớn!!!",
    "41":"Đem kí ức cất vào trong tủ\nCái gì cũ cứ để nó tự phai…",
    "42":"Hoa vô tình bỏ rơi cành lá\nNgười vô tình bỏ lỡ tơ duyên",
    "43":"Nghe nói anh có nhiều tâm sự\nThật tình cờ… em có cả vạn tâm tư!",
    "44":"Tưởng em là hoa chưa chủ\nAi ngờ em là chủ cả vườn hoa",
    "45":"Trăng kia ai vẽ mà tròn\nLòng anh ai trộm mà hoài nhớ thương"
    "46":"Khôn ba năm, dại một giờ.",
    "47":"Người khôn ăn nói nửa chừng\nĐể cho người dại vừa mừng vừa lo.",
    "48":"Khôn làm văn tế, dại làm văn bia.",
    "49":"Ăn cỗ đi trước, lội nước đi sau.",
    "50":"Chẳng có dại nào giống dại nào.",
    "51":"Ngu si hưởng thái bình",
    "52":"Thằng dại làm hại thằng khôn.",
    "53":"Khôn cho người ta sợ,\nDại cho người ta thương,\nDở dở ương ương tổ cho người ta ghét.",
    "54":"Vụng chèo khéo chống.",
    "55":"Vụng múa chê đất lệch.",
    "56":"Hay thì khen, hèn thì chê.",
    "57":"Mười quan tiền công,\n    Không bằng một đồng tiền thưởng.",
    "58":"Trâu chết để da, người chết để tiếng.",
    "59":"Tốt danh hơn lành áo.",
    "60":"Lắm người yêu hơn nhiều kẻ ghét.",
    "61":"Yêu trẻ, trẻ đến nhà; yêu già, già để phúc.",
    "62":"Yêu nhau chín bỏ làm mười\nCó mặt thì mắng, vắng mặt thì thương.",
    "63":"Yêu nhau lắm, cắn nhau đau.",
    "64":"Yêu nên tốt, ghét nên xấu.",
    "65":"Yêu ai yêu cả đường đi,\nGhét nhau ghét cả tông chi họ hàng.",
    "66":"Ghét nhau đào đất đổ đi",
    "67":"Người có lúc vinh lúc nhục,\nNước có lúc đục lúc trong.",
    "68":"Sướng lắm, khổ nhiều.",
    "69":"Thương người như thể thương thân",
    "70":"Lá lành đùm lá rách\nĂn nhạt mới biết thương mèo.",
    "71":"Bỏ thì thương, vương thì tội.",
    "72":"Ăn quả nhớ kẻ trồng cây.",
    "73":"Uống nước nhớ nguồn.",
    "74":"Một đêm nằm một năm ở.",
    "75":"Đường mòn, ân nghĩa không mòn.",
    "76":"Chanh chua chớ phụ, ngọt bòng chớ ham.",
    "77":"Hoài thóc nuôi cò rừng",
    "78":"Được chim bẻ ná, được cá quên nơm.",
    "79":"Ăn cháo đái bát.",
    "80":"Chưa khỏi rên đã quên thầy.",
    "81":"Có xương sông, tình phụ lá lốt.",
    "82":"Có trăng, phụ đèn.",
    "83":"Một câu nhịn là chín câu lành.",
    "84":"Tránh voi chẳng xấu mặt.",
    "85":"Con gà tức nhau tiếng gáy.",
    "86":"Đánh nhau chia gạo, chào nhau ăn cơm.",
    "87":"Cả giận mất khôn.",
    "88":"Hơi đâu mà giận người dưng.",
    "89":"Một đời kiện, chín đời thù.",
    "90":"Ăn ngay nói thật, mọi tật mọi lành.",
    "91":"Cây ngay chẳng sợ chết đứng",
    "92":"Có tật giật mình, có tình kinh trong bụng.",
    "93":"Thẳng mực tàu đau lòng gỗ.",
    "94":"Mất lòng trước, được lòng sau.",
    "95":"Mật ngọt chết ruồi,\nnhững nơi cay đắng là nơi thật thà.",
    "96":"Trâu đồng nào ăn cỏ đồng ấy.",
    "97":"Ăn cây nào rào cây ấy.",
    "98":"Thân trâu trâu lo, thân bò bò liệu.",
    "99":"Cha chung không ai khóc.",
    "100":"Cháy nhà hàng xóm, bình chân như vại.",
    "101":"Hoài tiền mua pháo, mượn người đốt.",
    "102":"Việc nhà thì nhác, việc chú bác thì siêng.",
    "103":"Có vay có trả, mới thỏa lòng nhau.",
    "104":"Cá mè một lứa.",
    "105":"Tắt đèn nhà ngói cũng như nhà tranh.",
    "106":"Làm quan ăn lộc vua, ở chùa ăn lộc phật.",
    "107":"Ngày dưng thì chẳng chắp gai,\nđến khi có cá mượn chài ai cho.",
    "108":"Người lười đất không lười.",
    "109":"Mồm miệng đỡ chân tay.",
    "110":"Giã gạo thì ốm, giã cốm thì khỏe.",
    "111":"Khéo ăn thì no, khéo co thì ấm.",
    "112":"Đo bò làm chuồng.",
    "113":"Yếu chân chạy trước.",
    "114":"Làm khi lành, để dành khi đau",
    "115":"Mất bò mới lo làm chuồng.",
    "116":"Có mình thì giữ.",
    "117":"Buôn tàu bán đất, không bằng ăn dè hà tiện.",
    "118":"Đãi cứt sáo lấy hạt đa, đãi cứt gà lấy hạt tấm.",
    "119":"Kiếm củi ba năm thiêu một giờ",
    "120":"Đời cha vo tròn, đời con bóp bẹp",
    "121":"Sông lở cát bồi",
    "122":"Được lòng ta, xót xa lòng người",
    "123":"Bói rẻ còn hơn ngồi không",
    "124":"Chẳng được con trắm con chép, cũng được mớ tép mớ tôm",
    "125":"Thả con săn sắt, bắt con cá rô",
    "126":"Lọt sàng xuống nia",
    "127":"Lá rụng về cội",
    "128":"Cơm không ăn, gạo còn đó",
    "129":"Gạo đổ, hót chẳng đầy thưng",
    "130":"Mất cả chì lẫn chài",
    "131":"Được một bữa cơm người, mất mười bữa cơm nhà.",
    "132":"Đã khó, chó cắn thêm",
    "133":"Biết tội đâu mà tránh, biết phúc đâu mà tìm.",
    "134":"Buồn ngủ lại gặp chiếu manh\nhay ăn làm biếng gặp anh đứng đường.",
    "135":"Đi đêm lắm có ngày gặp ma",
    "136":"Bốn chín chưa qua, năm ba đã tới",
    "137":"Tránh vỏ dưa, gặp vỏ dừa",
    "138":"Chạy trời không khỏi nắng",
    "139":"Thuốc chữa bệnh, chẳng chữa được mệnh",
    "140":"Khi nên, trời cũng chiều người",
    "141":"Năm ngón tay có ngón dài ngón ngắn",
    "142":"Ai uốn câu cho vừa miệng cá",
    "143":"Thánh cũng có khi nhầm",
    "144":"Bới bèo ra bọ",
    "145":"Đánh rắn phải đánh dập đầu",
    "146":"Đã tu thời tu cho trót.",
    "147":"Có chí thì nên.",
    "148":"Mưu cao chẳng bằng chí dày",
    "149":"Kiến tha lâu cũng đầy tổ",
    "150":"Có công mài sắt, có ngày nên kim",
    "151":"Năng nhặt chặt bị",
    "152":"Trăm bó đuốc cũng vớ được con ếch",
    "153":"Còn nước còn tát",
    "154":"Thắng không kiêu, bại không nản",
    "155":"Sóng cả chớ ngã tay chèo",
    "156":"Vua thua thằng liều",
    "157":"Con mẹ đẻ con con\nCòn gà trống gà mái thì còn gà giò ",
    "158":"Trời không đóng cửa ai",
    "159":"Ai giàu ba họ, ai khó ba đời",
    "160":"Cờ đến tay ai người ấy phất",
    "161":"Bút sa, gà chết",
    "162":"Xay lúa thì thôi ẵm em",
    "163":"Lắm sãi không ai đóng cửa chùa",
    "164":"Bụng làm da chịu",
    "165":"Có gan ăn cắp, có gan chịu đòn",
    "166":"Chó gầy hổ mặt người nuôi",
    "167":"Bắn súng không nên, phải đền đạn",
    "168":"Trăm dâu đổ đầu tằm ",
    "169":"Trọc đầu càng mát",
    "170":"Mèo nhỏ bắt chuột con",
    "171":"Rộng làm kép, hẹp làm đơn",
    "172":"Ốc chẳng mang nổi mình ốc\nốc lại còn mang cọc cho rêu",
    "173":"Ai dám đánh đu với tinh ",
    "174":"Chó ghẻ có mỡ đằng đuôi",
    "175":"Chửa học bò đã lo học chạy",
    "176":"Chưa võ bọng cứt đã đòi bay bổng",
    "177":"Ếch ngồi đáy giếng, coi trời bằng vung",
    "178":"Chó cậy gần nhà, gà cậy gần chuồng",
    "179":"Thân lừa ưa nặng",
    "180":"Mạnh dùng sức, yếu dùng chước ",
    "181":"Có cháo hỏi chè",
    "182":"Đứng núi này trông núi nọ",
    "183":"Điếc hay ngóng, ngọng hay nói",
    "184":"Ăn mày đòi xôi gấc",
    "185":"Già còn chơi trống bỏi",
    "186":"Con có khóc mẹ mới cho bú",
    "187":"Ai biết ngứa đâu mà gãi",
    "188":"Ếch no khó nhử mồi",
    "189":"Chê của nào trời trao của ấy",
    "190":"Chê tôm lại phải ăn tôm,\nchê rau muống héo, lại ôm dưa già.",
    "191":"Ăn trứng thì đừng ăn con.",
    "192":"Được thể dễ nói khoác",
    "193":"Tế sớm khỏi ruồi",
    "194":"Gió chiều nào che chiều ấy",
    "195":"Châu chấu thấy đỏ lửa thì vào.",
    "196":"Theo đóm ăn tàn",
    "197":"Nhờ gió bẻ măng",
    "198":"Đục nước béo cò",
    "199":"Giậu đổ bìm leo",
    "200":"Chợ chưa họp, kẻ cắp đã đến",
    "201":"Vỏ quýt dày có móng tay nhọn",
    "202":"Kẻ cắp gặp bà già",
    "203":"Mềm nắn rắn buông",
    "204":"Lành làm gáo, vỡ làm môi",
    "205":"Hòn đất ném đi, hòn chì ném lại",
    "206":"Mâm cao đánh ngã bát đầy",
    "207":"Ở xứ mù anh chột làm vua",
    "208":"Gần chùa gọi bụt bằng anh",
    "209":"Cháy nhà ra mặt chuột",
    "210":"Đâm lao phải theo lao",
    "211":"Trót đa mang phải đeo bòng",
    "212":"Sai một li đi một dặm",
    "213":"Tham thì thâm, nhầm thì thiệt",
    "214":"Chết sông chết suối,\nkhông ai chết đuối đọi đèn",
    "215":"Có nước có cá",
    "216":"Thóc đâu bồ câu đấy",
    "217":"Nằm giữa không mất phần chân",
    "218":"Cơm vào miệng còn rơi",
    "219":"Một mất mười ngờ",
    "220":"Cóc có gan cóc, kiến có gan kiến.",
    "221":"Máu trâu cũng như máu bò",
    "222":"Lòng vả cũng như lòng sung",
    "223":"Ba thưng cũng vào một đấu",
    "224":"Suy bụng ta ra bụng người",
    "225":"Bói ra ma, quét nhà ra rác",
    "226":"Giang sơn đâu, anh hùng đấy",
    "227":"Cơm đâu no chó, thóc đâu no gà",
    "228":"Quá mù ra mưa.",
    "229":"Chín quá hóa nẫu",
    "230":"Trèo cao ngã đau",
    "231":"Thắm lắm phai nhiều",
    "232":"Già néo đứt dây",
    "233":"Chọn mặt gửi vàng",
    "234":"Đi với phật mặc áo cà sa\nđi với ma mặc áo giấy",
    "235":"To đầu khó chui",
    "236":"Ở bầu thì tròn, ở ống thì dài",
    "237":"Rau nào sâu nấy",
    "238":"Gần lửa rát mặt",
    "239":"Cháy thành vạ lây",
    "240":"Gần nhà giàu đau răng ăn cốm\ngần kẻ trộm ốm lưng chịu đòn",
    "241":"Lụt thì lụt cả làng",
    "242":"Được mùa thầy chùa no bụng",
    "243":"Trâu bò húc nhau, ruồi muỗi chết",
    "244":"Rút dây động rừng",
    "245":"Môi hở răng lạnh",
    "246":"Đánh chó ngó chủ nhà",
    "247":"Yêu con chị vị con em",
    "248":"Cách sông nên phải lụy đò",
    "249":"Há miệng mắc quai",
    "250":"Muốn tròn thì phải có khuôn,\nmuốn vuông phải có thước",
    "251":"Đầu xuôi đuôi lọt",
    "252":"Vạn sự khởi đầu nan",
    "253":"Cũ người mới ta",
    "254":"Trước lạ sau quen",
    "255":"Đánh bạc quen tay\nngủ ngày quen mắt",
    "256":"Ăn vặt quen mồm",
    "257":"Ngựa quen đường cũ",
    "258":"Người làm sao, chiêm bao làm vậy",
    "259":"Dốt đặc còn hơn hay chữ lỏng",
    "260":"Tích tiểu thành đại",
    "261":"Góp gió thành bão, góp cây nên rừng",
    "262":"Ba người đánh một, không chột cũng què",
    "263":"Vét nồi ba mươi cũng đầy niêu nốt",
    "264":"Xấu đều hơn tốt lõi",
    "265":"Xanh không thủng cá đi đằng nào",
    "266":"Có bột mới gột nên hồ",
    "267":"Ôm rơm nặng bụng",
    "268":"Chơi dao sắc có ngày đứt tay"
	}
}
